-- MySQL Script generated by MySQL Workbench
-- Sun 07 Jun 2026 01:00:38 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema CourseGrades
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CourseGrades
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CourseGrades` DEFAULT CHARACTER SET utf8mb3 ;
USE `CourseGrades` ;

-- -----------------------------------------------------
-- Table `CourseGrades`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseGrades`.`USERS` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `failed_attempts` INT NULL DEFAULT '0',
  `account_locked` TINYINT(1) NULL DEFAULT '0',
  `locked_until` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`username`),
  INDEX `idx_users_username_locked` (`username` ASC, `account_locked` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CourseGrades`.`PROFESSORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseGrades`.`PROFESSORS` (
  `AFM` INT NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Surname` VARCHAR(45) NULL DEFAULT NULL,
  `Department` VARCHAR(45) NULL DEFAULT NULL,
  `USERS_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AFM`, `USERS_username`),
  INDEX `fk_PROFESSORS_USERS1_idx` (`USERS_username` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESSORS_USERS1`
    FOREIGN KEY (`USERS_username`)
    REFERENCES `CourseGrades`.`USERS` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CourseGrades`.`COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseGrades`.`COURSE` (
  `idCOURSE` INT NOT NULL,
  `CourseTitle` VARCHAR(60) NULL DEFAULT NULL,
  `CourseSemester` VARCHAR(25) NULL DEFAULT NULL,
  `PROFESSORS_AFM` INT NOT NULL,
  PRIMARY KEY (`idCOURSE`),
  INDEX `fk_COURSE_PROFESSORS_idx` (`PROFESSORS_AFM` ASC) VISIBLE,
  CONSTRAINT `fk_COURSE_PROFESSORS`
    FOREIGN KEY (`PROFESSORS_AFM`)
    REFERENCES `CourseGrades`.`PROFESSORS` (`AFM`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CourseGrades`.`STUDENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseGrades`.`STUDENTS` (
  `RegistrationNumber` INT NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Surname` VARCHAR(45) NULL DEFAULT NULL,
  `Department` VARCHAR(45) NULL DEFAULT NULL,
  `USERS_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RegistrationNumber`, `USERS_username`),
  INDEX `fk_STUDENTS_USERS1_idx` (`USERS_username` ASC) VISIBLE,
  CONSTRAINT `fk_STUDENTS_USERS1`
    FOREIGN KEY (`USERS_username`)
    REFERENCES `CourseGrades`.`USERS` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CourseGrades`.`COURSE_has_STUDENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseGrades`.`COURSE_has_STUDENTS` (
  `COURSE_idCOURSE` INT NOT NULL,
  `STUDENTS_RegistrationNumber` INT NOT NULL,
  `GradeCourseStudent` INT NULL DEFAULT NULL,
  PRIMARY KEY (`COURSE_idCOURSE`, `STUDENTS_RegistrationNumber`),
  INDEX `fk_COURSE_has_STUDENTS_STUDENTS1_idx` (`STUDENTS_RegistrationNumber` ASC) VISIBLE,
  INDEX `fk_COURSE_has_STUDENTS_COURSE1_idx` (`COURSE_idCOURSE` ASC) VISIBLE,
  CONSTRAINT `fk_COURSE_has_STUDENTS_COURSE1`
    FOREIGN KEY (`COURSE_idCOURSE`)
    REFERENCES `CourseGrades`.`COURSE` (`idCOURSE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_COURSE_has_STUDENTS_STUDENTS1`
    FOREIGN KEY (`STUDENTS_RegistrationNumber`)
    REFERENCES `CourseGrades`.`STUDENTS` (`RegistrationNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
