-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.student
(
    username "char",
    id numeric,
    password "char",
    student_grade numeric,
    course "char",
    name "char",
    surename "char",
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.professor
(
    username "char",
    id numeric,
    password "char",
    grade numeric,
    course "char",
    name "char",
    surename "char",
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.secretary
(
    username "char",
    id numeric,
    password "char",
    courses "char",
    name "char",
    surename "char",
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    course_name "char",
    course_semester numeric,
    course_grade numeric
);

CREATE TABLE IF NOT EXISTS public.grades
(
    grade numeric
);

ALTER TABLE IF EXISTS public.student
    ADD FOREIGN KEY (student_grade)
    REFERENCES public.courses (course_grade) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.student
    ADD FOREIGN KEY (course)
    REFERENCES public.courses (course_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.professor
    ADD FOREIGN KEY (course)
    REFERENCES public.courses (course_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.secretary
    ADD FOREIGN KEY (courses)
    REFERENCES public.courses (course_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.courses
    ADD FOREIGN KEY (course_grade)
    REFERENCES public.grades (grade) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.grades
    ADD FOREIGN KEY (grade)
    REFERENCES public.professor (grade) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;